pr: ["master"]

jobs:
  - job: tests
    displayName: "Tests"
    steps:
      - template: ci/install-rust.yml
        parameters:
          rust_version: stable
      - bash: |
          export RUST_BACKTRACE=1
          cargo install cargo-readme || exit
          cargo test --all || exit
        displayName: "Run cargo test"
  - job: check_benches
    displayName: "Check that benches build"
    steps:
      - template: ci/install-rust.yml
        parameters:
          rust_version: stable
      - bash: |
          cargo check --benches || exit
        displayName: "Run cargo check"
